#lang scheme

;;; ===========
;;; Section 1.2
;;; ===========


;;; Exercise 1.9
;;; ------------
;;; Use the substitution model to illustrate the process generated by the
;;; following procedures evaluating (+ 4 5). Are the processes iterative or
;;; recursive?

(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))

(+ 4 5)
;; (inc (+ 3 5))
;; (inc (inc (+ 2 5)))
;; (inc (inc (inc (+ 1 5))))
;; (inc (inc (inc (inc (+ 0 5)))))
;; (inc (inc (inc (inc 5))))
;; (inc (inc (inc 6)))
;; (inc (inc 7))
;; (inc 8)
;; 9
;; This is a recursive process. The state is not saved from one step to the next
;; and is dependent on the call stack.

(define (+ a b)
  (if (= a 0)
      b
      (+ (dec a) (inc b))))

(+ 4 5)
;; (+ 3 6)
;; (+ 2 7)
;; (+ 1 8)
;; (+ 0 9)
;; 9
;; This is an iterative process. The state is saved from one step to the next
;; and is not dependent on the call stack. If the procedure is stopped, it can
;; be resumed with the same values the procedure's state contained upon
;; termination and the answer will still be correct.
